#
# Makefile for gemma, a minimal GEM library
#

SHELL = /bin/sh
SUBDIRS = documentation libgemma libslb src

srcdir = .
top_srcdir = ..
subdir = gemma

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
