; Generated by mit2mot v1.0.4 on Apr 08 2000 12:49:36

	.globl	_aes
	.globl	_vdi
	.globl	_vq_gdos
	.globl	_vq_vgdos

_aes:	move.l	4(sp), d1
	move.w	#200, d0
	movem.l	d2/a2, -(sp)	; backup registers
	trap	#2
	movem.l	(sp)+, d2/a2	; restore registers
	rts

_vdi:	move.l	4(sp), d1
	moveq	#115, d0
	movem.l	d2/a2, -(sp)	; backup registers
	trap	#2
	movem.l	(sp)+, d2/a2	; restore registers
	rts

_vq_gdos:
	moveq	#-2, d0
	movem.l	d2/a2, -(sp)	; backup registers
	trap	#2
	movem.l	(sp)+, d2/a2	; restore registers
	cmp.w	#-2, d0
	sne	d0
	ext.w	d0
	rts

_vq_vgdos:
	moveq	#-2, d0
	movem.l	d2/a2, -(sp)	; backup registers
	trap	#2
	movem.l	(sp)+, d2/a2	; restore registers
	rts
