/*
 *  $Id$
 */

#include "gem_aesP.h"

/** returns important information regarding the
 *  physical workstation currently in use by the AES.
 *
 *  @param wcell
 *  @param hcell are WORD pointers which on function exit
 *               will be filled in with the width and height, respectively,
 *               of the current system character set. \n
 *             [option CHECK_NULLPTR] wcell and/or hcell may be NULL
 *  @param  wbox
 *  @param  hbox are WORD pointers which on function exit
 *               will be filled in with the width and height, respectively,
 *               of the minimum bounding box of a BOXCHAR character. \n
 *             [option CHECK_NULLPTR] wbox and/or hbox may be NULL
 *  @param  device (TODO: doc wanted). \n
 *             [option CHECK_NULLPTR] device may be NULL
 *  @param global_aes global AES array
 *
 *  @return the VDI handle for the current physical workstation used
 *          by the AES which is required to open a virtual screen
 *          workstation.
 *
 *  @since All AES versions.
 *
 *  @sa v_opnvwk()
 *
 *  @note There is currently no defined method of handling an error
 *        generated by this function.
 *
 */

short
mt_graf_xhandle (short *wcell, short *hcell, short *wbox, short *hbox, short *device, short *global_aes)
{
#if !(CHECK_NULLPTR)
	short *ptr;
#endif

	AES_PARAMS(77,0,6,0,0);

	AES_TRAP(aes_params);

#if CHECK_NULLPTR
	if (wcell)	*wcell = aes_intout[1];
	if (hcell)	*hcell = aes_intout[2];
	if (wbox)	*wbox  = aes_intout[3];
	if (hbox)	*hbox  = aes_intout[4];
	if (device) *device  = aes_intout[5];
#else
	ptr = &aes_intout[1];
	*wcell = *(ptr ++);									/* [1] */
	*hcell = *(ptr ++);									/* [2] */
	*wbox  = *(ptr ++);									/* [3] */
	*hbox  = *(ptr ++);									/* [4] */
	*device= *(ptr);									/* [4] */
#endif

	return aes_intout[0];
}
