/*
 *  $Id$
 */

#include "gem_aesP.h"

/** allows the user to change the size of
 *  a box outline with a fixed starting point.
 *
 *  @param bx
 *  @param by define the fixed upper-left corner of the box to
 *               stretch or shrink.
 *  @param mw
 *  @param mh specify the minimum width and height that
 *               the rectangle can be shrunk to.
 *  @param rw
 *  @param rh are WORD pointers which will be filled in
 *               with the ending width and height of the box when the mouse
 *               button is released.
 *  @param global_aes global AES array
 *
 *  @return 0 if an error occurred or non-zero otherwise.
 *
 *  @since All AES versions.
 *
 *  @sa mt_graf_dragbox(), mt_graf_slidebox()
 *
 *  This function should only be entered when the user has
 *  depressed the mouse button as it returns when the mouse
 *  button is released.
 *
 *  @note There is currently no defined method of handling an error
 *        generated by this function.
 *
 */

short
mt_graf_rubberbox(short bx, short by, short mw, short mh, short *rw, short *rh, short *global_aes)
{
	AES_PARAMS(70,4,3,0,0);

	aes_intin[0] = bx;
	aes_intin[1] = by;
	aes_intin[2] = mw;
	aes_intin[3] = mh;

	AES_TRAP(aes_params);

	*rw = aes_intout[1];
	*rh = aes_intout[2];

	return aes_intout[0];
}

#ifdef graf_rubberbox
#undef graf_rubberbox
#endif
short
graf_rubberbox(short bx, short by, short mw, short mh, short *rw, short *rh)
{
	return(mt_graf_rubberbox( bx,  by, mw, mh, rw, rh, aes_global));
}

short
graf_rubbbox(short bx, short by, short mw, short mh, short *rw, short *rh)
{
	return(mt_graf_rubberbox( bx,  by, mw, mh, rw, rh, aes_global));
}
