/*
 *  $Id$
 */

#include "gem_aesP.h"

/** returns important information regarding the
 *  physical workstation currently in use by the AES.
 *
 *  @param wcell
 *  @param hcell are WORD pointers which on function exit
 *               will be filled in with the width and height, respectively,
 *               of the current system character set.
 *  @param  wbox
 *  @param  hbox are WORD pointers which on function exit
 *               will be filled in with the width and height, respectively,
 *               of the minimum bounding box of a BOXCHAR character.
 *  @param global_aes global AES array
 *
 *  @return the VDI handle for the current physical workstation used
 *          by the AES which is required to open a virtual screen
 *          workstation.
 *
 *  @since All AES versions.
 *
 *  @sa v_opnvwk()
 *
 *  @note There is currently no defined method of handling an error
 *        generated by this function.
 *
 */

short
mt_graf_handle (short *wcell, short *hcell, short *wbox, short *hbox, short *global_aes)
{
	short *ptr;

	AES_PARAMS(77,0,5,0,0);

	AES_TRAP(aes_params);

	ptr = &aes_intout[1];
	*wcell = *(ptr ++);									/* [1] */
	*hcell = *(ptr ++);									/* [2] */
	*wbox  = *(ptr ++);									/* [3] */
	*hbox  = *(ptr);									/* [4] */

	return aes_intout[0];
}

#ifdef graf_handle
#undef graf_handle
#endif
short
graf_handle(short *wcell, short *hcell, short *wbox, short *hbox)
{
	return(mt_graf_handle(wcell, hcell, wbox, hbox, aes_global));
}
